# Generated by Django 4.2.13 on 2025-02-10 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Repoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcounty',
            name='subcounty_county',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcounty', to='Repoapp.county'),
            preserve_default=False,
        ),
    ]
