# Generated by Django 4.2.13 on 2025-02-24 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Repoapp', '0002_subcounty_subcounty_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_subcounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountnames', to='Repoapp.subcounty'),
        ),
        migrations.CreateModel(
            name='Dashboards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Role', models.CharField(max_length=255)),
                ('Community_Health_Unit', models.CharField(max_length=255)),
                ('Username', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('Admin', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('account_county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Repoapp.county')),
                ('account_subcounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboardnames', to='Repoapp.subcounty')),
                ('admin_profile', models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='Repoapp.profile')),
            ],
            options={
                'verbose_name': 'My Dashboards',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['-pub_date'],
            },
        ),
    ]
