# Generated by Django 4.2.13 on 2025-02-24 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Repoapp', '0003_alter_accounts_account_subcounty_dashboards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboards',
            name='Admin',
        ),
    ]
