# Generated by Django 4.2.13 on 2025-02-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repoapp', '0004_remove_dashboards_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='Area_UUID',
            field=models.CharField(blank=True, default='1', max_length=1000, null=True),
        ),
    ]
