# Generated by Django 4.2.13 on 2025-02-24 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Repoapp', '0005_accounts_area_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_subcounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcounty', to='Repoapp.subcounty'),
        ),
    ]
