# Generated by Django 4.2.13 on 2025-05-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repoapp', '0007_alter_accounts_area_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='RDHSO', max_length=100),
        ),
    ]
