# Generated by Django 4.2.13 on 2026-02-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repoapp', '0009_countries_county_county_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allowed_counties',
            field=models.ManyToManyField(blank=True, related_name='allowed_users', to='Repoapp.county'),
        ),
        migrations.AddField(
            model_name='profile',
            name='allowed_countries',
            field=models.ManyToManyField(blank=True, related_name='allowed_users', to='Repoapp.countries'),
        ),
        migrations.AddField(
            model_name='profile',
            name='allowed_subcounties',
            field=models.ManyToManyField(blank=True, related_name='allowed_users', to='Repoapp.subcounty'),
        ),
    ]
