# Generated by Django 4.2.13 on 2026-02-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repoapp', '0010_profile_allowed_counties_profile_allowed_countries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='account_country',
            field=models.CharField(default='Kenya', max_length=255),
        ),
        migrations.AddField(
            model_name='dashboards',
            name='account_country',
            field=models.CharField(default='Kenya', max_length=255),
        ),
        migrations.AddField(
            model_name='lmsaccounts',
            name='account_country',
            field=models.CharField(default='Kenya', max_length=255),
        ),
    ]
